pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - files~=^builds/
      - files~=^changelogs/
      - check-success=validate-json
      - "#files=2"
      - author=@PixelExtended/maintainers
    actions:
     merge:
        method: merge
