# This is a basic workflow to trigger donation post in tg channel every week

name: First Cron Job
on:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: TG Notify
      env:
        TOKEN: ${{ secrets.TOKEN }}
        CHAT_ID: ${{ secrets.CHAT }}
      run: bash donate.sh
